export { default as apiClient } from './client'
export * from './config'
export { startIndex, getIndexStatus, listIndexTasks } from './indexing'
export * from './search'
export * from './benchmark'
export * from './providers'
export * from './profiles'
export { searchTest, getDebugInfo } from './debug'
export type { IndexTask, IndexTaskStatus } from './debug'