/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API root endpoint */
        get: operations["api_root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current configuration */
        get: operations["get_config"];
        /** Update configuration */
        put: operations["update_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start indexing task */
        post: operations["start_index"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/index/status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get indexing task status */
        get: operations["get_index_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Perform search query */
        post: operations["search"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all collections */
        get: operations["list_collections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run benchmark comparison */
        post: operations["run_benchmark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Error type */
            error: string;
            /** @description Human-readable error message */
            message: string;
            /** @description Additional error details */
            detail?: Record<string, never> | null;
        };
        SuccessResponse: {
            /** @default success */
            status: string;
            message: string;
        };
        AppConfig: {
            server?: components["schemas"]["ServerConfig"];
            chroma?: components["schemas"]["ChromaConfig"];
            providers?: components["schemas"]["ProvidersConfig"];
            indexer?: components["schemas"]["IndexerConfig"];
            watcher?: components["schemas"]["WatcherConfig"];
            logging?: components["schemas"]["LoggingConfig"];
            hybrid?: components["schemas"]["HybridConfig"];
            cors?: components["schemas"]["CORSConfig"];
        };
        ServerConfig: {
            /** @default 0.0.0.0 */
            host: string;
            /** @default 8818 */
            port: number;
            /** @default true */
            debug: boolean;
        };
        ChromaConfig: {
            /** @default ./data/chroma */
            persist_dir: string;
            host?: string | null;
            port?: number | null;
        };
        ProvidersConfig: {
            embedding?: components["schemas"]["ProviderCategory"];
            rerank?: components["schemas"]["ProviderCategory"];
            llm?: components["schemas"]["ProviderCategory"];
            vectorstore?: components["schemas"]["ProviderCategory"];
        };
        ProviderCategory: {
            default?: string;
            instances?: components["schemas"]["ProviderInstance"][];
        };
        ProviderInstance: {
            name: string;
            type: string;
            model: string;
            base_url?: string | null;
            dimension?: number | null;
        };
        IndexerConfig: {
            /** @default 500 */
            chunk_size: number;
            /** @default 50 */
            chunk_overlap: number;
            /** @default 1048576 */
            max_file_size: number;
            file_types?: string[];
            exclude_dirs?: string[];
        };
        WatcherConfig: {
            /** @default true */
            enabled: boolean;
            /** @default 1 */
            debounce_seconds: number;
        };
        LoggingConfig: {
            /** @default INFO */
            level: string;
            format?: string;
            file?: string | null;
        };
        HybridConfig: {
            /** @default 0.5 */
            alpha: number;
            /** @default 0.5 */
            beta: number;
            /** @default 60 */
            rrf_k: number;
            /** @default ./data/bm25 */
            bm25_persist_dir: string;
        };
        CORSConfig: {
            /**
             * @default [
             *       "http://localhost:3315",
             *       "http://127.0.0.1:3315"
             *     ]
             */
            origins: string[];
            /** @default true */
            allow_credentials: boolean;
            /**
             * @default [
             *       "*"
             *     ]
             */
            allow_methods: string[];
            /**
             * @default [
             *       "*"
             *     ]
             */
            allow_headers: string[];
        };
        ConfigUpdateRequest: {
            server?: components["schemas"]["ServerConfig"];
            chroma?: components["schemas"]["ChromaConfig"];
            providers?: components["schemas"]["ProvidersConfig"];
            indexer?: components["schemas"]["IndexerConfig"];
            logging?: components["schemas"]["LoggingConfig"];
            hybrid?: components["schemas"]["HybridConfig"];
            watcher?: components["schemas"]["WatcherConfig"];
        };
        IndexRequest: {
            /** @description Directory or file path to index */
            path: string;
            /** @default default */
            collection_name: string;
            embedding_provider?: string | null;
            chunk_size?: number | null;
            chunk_overlap?: number | null;
            /** @default true */
            recursive: boolean;
        };
        IndexTaskStatus: {
            task_id: string;
            status: components["schemas"]["TaskStatus"];
            /** @default 0 */
            progress: number;
            message?: string;
            total_files?: number;
            processed_files?: number;
            total_chunks?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            error?: string | null;
        };
        /** @enum {string} */
        TaskStatus: "pending" | "running" | "completed" | "failed";
        IndexResponse: {
            task_id: string;
            /** @default Indexing task started */
            message: string;
            status_url: string;
        };
        SearchRequest: {
            query: string;
            /** @default default */
            collection_name: string;
            /** @default 5 */
            top_k: number;
            embedding_provider?: string | null;
            rerank_provider?: string | null;
            /** @default true */
            use_rerank: boolean;
        };
        SearchResult: {
            id: string;
            text: string;
            score: number;
            metadata?: {
                [key: string]: unknown;
            };
            rerank_score?: number | null;
        };
        SearchResponse: {
            query: string;
            results: components["schemas"]["SearchResult"][];
            total: number;
            collection: string;
            embedding_provider: string;
            rerank_provider?: string | null;
        };
        BenchmarkRequest: {
            query: string;
            /** @default default */
            collection_name: string;
            configs: components["schemas"]["BenchmarkConfig"][];
        };
        BenchmarkConfig: {
            name: string;
            embedding_provider: string;
            rerank_provider?: string | null;
            /** @default 5 */
            top_k: number;
        };
        BenchmarkResult: {
            config_name: string;
            results: components["schemas"]["SearchResult"][];
            latency_ms: number;
            embedding_provider: string;
            rerank_provider?: string | null;
        };
        BenchmarkResponse: {
            query: string;
            collection: string;
            results: components["schemas"]["BenchmarkResult"][];
            total_latency_ms: number;
        };
        CollectionInfo: {
            name: string;
            count: number;
            metadata?: {
                [key: string]: unknown;
            };
        };
        CollectionsListResponse: {
            collections: components["schemas"]["CollectionInfo"][];
            total: number;
        };
        CollectionDeleteResponse: {
            name: string;
            /** @default Collection deleted successfully */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example healthy */
                        status?: string;
                        /** @example RagHubMCP */
                        service?: string;
                        /** @example 0.1.0 */
                        version?: string;
                    };
                };
            };
        };
    };
    api_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name?: string;
                        version?: string;
                        endpoints?: string[];
                    };
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    update_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Configuration updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    start_index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexRequest"];
            };
        };
        responses: {
            /** @description Indexing started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexResponse"];
                };
            };
        };
    };
    get_index_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexTaskStatus"];
                };
            };
            /** @description Task not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    list_collections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of collections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectionsListResponse"];
                };
            };
        };
    };
    run_benchmark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenchmarkRequest"];
            };
        };
        responses: {
            /** @description Benchmark results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenchmarkResponse"];
                };
            };
        };
    };
}
